<?php
if (($gamezone_slider_sc = gamezone_get_theme_option('front_page_title_shortcode')) != '' && strpos($gamezone_slider_sc, '[')!==false && strpos($gamezone_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$gamezone_anchor_icon = gamezone_get_theme_option('front_page_title_anchor_icon');	
		$gamezone_anchor_text = gamezone_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($gamezone_anchor_icon) || !empty($gamezone_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($gamezone_anchor_icon) ? ' icon="'.esc_attr($gamezone_anchor_icon).'"' : '')
											. (!empty($gamezone_anchor_text) ? ' title="'.esc_attr($gamezone_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($gamezone_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$gamezone_scheme = gamezone_get_theme_option('front_page_title_scheme');
				if (!gamezone_is_inherit($gamezone_scheme)) echo ' scheme_'.esc_attr($gamezone_scheme);
				echo ' front_page_section_paddings_'.esc_attr(gamezone_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$gamezone_css = '';
			$gamezone_bg_image = gamezone_get_theme_option('front_page_title_bg_image');
			if (!empty($gamezone_bg_image)) 
				$gamezone_css .= 'background-image: url('.esc_url(gamezone_get_attachment_url($gamezone_bg_image)).');';
			if (!empty($gamezone_css))
				echo ' style="' . esc_attr($gamezone_css) . '"';
	?>><?php
		// Add anchor
		$gamezone_anchor_icon = gamezone_get_theme_option('front_page_title_anchor_icon');	
		$gamezone_anchor_text = gamezone_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($gamezone_anchor_icon) || !empty($gamezone_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($gamezone_anchor_icon) ? ' icon="'.esc_attr($gamezone_anchor_icon).'"' : '')
											. (!empty($gamezone_anchor_text) ? ' title="'.esc_attr($gamezone_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (gamezone_get_theme_option('front_page_title_fullheight'))
				echo ' gamezone-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$gamezone_css = '';
				$gamezone_bg_mask = gamezone_get_theme_option('front_page_title_bg_mask');
				$gamezone_bg_color = gamezone_get_theme_option('front_page_title_bg_color');
				if (!empty($gamezone_bg_color) && $gamezone_bg_mask > 0)
					$gamezone_css .= 'background-color: '.esc_attr($gamezone_bg_mask==1
																		? $gamezone_bg_color
																		: gamezone_hex2rgba($gamezone_bg_color, $gamezone_bg_mask)
																	).';';
				if (!empty($gamezone_css))
					echo ' style="' . esc_attr($gamezone_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$gamezone_caption = gamezone_get_theme_option('front_page_title_caption');
				if (!empty($gamezone_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($gamezone_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses($gamezone_caption, 'gamezone_kses_content'); ?></h1><?php
				}
			
				// Description (text)
				$gamezone_description = gamezone_get_theme_option('front_page_title_description');
				if (!empty($gamezone_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($gamezone_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses(wpautop($gamezone_description), 'gamezone_kses_content'); ?></div><?php
				}
				
				// Buttons
				if (gamezone_get_theme_option('front_page_title_button1_link')!='' || gamezone_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						gamezone_show_layout(gamezone_customizer_partial_refresh_front_page_title_button1_link());
						gamezone_show_layout(gamezone_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}